scikit-learn
load() is used to load pre-existing datasets, fetch() is used to download and load datasets from online sources, and make() is used to generate synthetic datasets.

In [2]:
from sklearn import datasets

In [3]:
iris = datasets.load_iris()
print(iris['data'][:3])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]]


In [4]:
import numpy as np
import pandas as pd

In [5]:
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
describe_info = df.describe()
print(describe_info)

       sepal length (cm)  sepal width (cm)  petal length (cm)   
count         150.000000        150.000000         150.000000  \
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)  
count        150.000000  
mean           1.199333  
std            0.762238  
min            0.100000  
25%            0.300000  
50%            1.300000  
75%            1.800000  
max            2.500000  


 Examples
    --------
    >>> np.unique([1, 1, 2, 2, 3, 3])
    array([1, 2, 3])
    >>> a = np.array([[1, 1], [2, 3]])
    >>> np.unique(a)
    array([1, 2, 3])


In [6]:
print(np.unique(iris['target']))

[0 1 2]


In [7]:
print(iris['feature_names'])

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [8]:
print(iris['target_names'])

['setosa' 'versicolor' 'virginica']


fetch

In [11]:
from sklearn.datasets import fetch_lfw_people

In [ ]:
# lfw_people = fetch_lfw_people(min_faces_per_person=70,resize=40)
# lfw_people = fetch_lfw_people()

In [ ]:
# for name in lfw_people.target_names:
#     print(name)

In [ ]:
from sklearn.datasets import fetch_mldata

In [ ]:
# mnist = fetch_mldata('MNIST original',data_home=custom_data_home)

In [ ]:
# print(mnist.data.shape)

In [ ]:
# print(mnist.target.shape)

In [ ]:
# print(np.unique(mnist.target))