In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3]).reshape(-1,1)

In [5]:
a.shape

(3, 1)

In [6]:
a

array([[1],
       [2],
       [3]])

In [7]:
b = np.array([4,5,6]).reshape(-1,1)

In [8]:
b

array([[4],
       [5],
       [6]])

In [9]:
a + b

array([[5],
       [7],
       [9]])

In [10]:
a - b

array([[-3],
       [-3],
       [-3]])

In [11]:
a * b

array([[ 4],
       [10],
       [18]])

In [12]:
a / b

array([[0.25],
       [0.4 ],
       [0.5 ]])