In [13]:
import numpy as np

matrix

In [ ]:
np.mat([[1,2],[3,4]])

In [30]:
x = np.array([[1,2],[3,4]])

In [31]:
m = np.asmatrix(x)

In [32]:
x[0,0] = 5

In [33]:
m

matrix([[5, 2],
        [3, 4]])

linear computation

In [35]:
A = np.array([[1,2],[3,4]])

In [36]:
A

array([[1, 2],
       [3, 4]])

In [37]:
A = np.array([[1,2],[3,4]])

In [38]:
A = np.mat([[1,2],[3,4]])

In [39]:
A

matrix([[1, 2],
        [3, 4]])

In [40]:
B = np.mat([[1,1],[1,1]])

In [41]:
B

matrix([[1, 1],
        [1, 1]])

In [42]:
A + B

matrix([[2, 3],
        [4, 5]])

In [43]:
A - B

matrix([[0, 1],
        [2, 3]])

In [44]:
B = np.mat([[5,6],[7,8]])

In [45]:
A * B

matrix([[19, 22],
        [43, 50]])

In [46]:
A = np.mat([[1,2,3],[4,5,6]])

In [47]:
B = np.mat([[1,2],[3,4],[5,6]])

In [48]:
A * B

matrix([[22, 28],
        [49, 64]])

In [49]:
B * A

matrix([[ 9, 12, 15],
        [19, 26, 33],
        [29, 40, 51]])

In [50]:
A * B

matrix([[22, 28],
        [49, 64]])

In [51]:
B * A

matrix([[ 9, 12, 15],
        [19, 26, 33],
        [29, 40, 51]])

In [52]:
np.dot(A,B)

matrix([[22, 28],
        [49, 64]])

In [53]:
np.dot(B,A)

matrix([[ 9, 12, 15],
        [19, 26, 33],
        [29, 40, 51]])

In [54]:
A @ B

matrix([[22, 28],
        [49, 64]])

In [55]:
B @ A

matrix([[ 9, 12, 15],
        [19, 26, 33],
        [29, 40, 51]])

determinant

In [56]:
A = np.mat([[1,0,3],[2,0,1],[3,3,5]])

In [57]:
np.linalg.det(A)

15.0

In [59]:
A = np.mat([[1,-1,2,-3,1],[-3,3,-7,9,-5],[2,0,4,-2,1],[3,-5,7,-14,6],[4,-4,10,-10,2]])

In [60]:
A

matrix([[  1,  -1,   2,  -3,   1],
        [ -3,   3,  -7,   9,  -5],
        [  2,   0,   4,  -2,   1],
        [  3,  -5,   7, -14,   6],
        [  4,  -4,  10, -10,   2]])

In [61]:
np.linalg.det(A)

11.999999999999995

inverse matrix

In [62]:
A = np.mat([[2,3,1],[0,1,3],[1,2,5]])

In [63]:
np.linalg.inv(A)

matrix([[-0.16666667, -2.16666667,  1.33333333],
        [ 0.5       ,  1.5       , -1.        ],
        [-0.16666667, -0.16666667,  0.33333333]])